alias gst='git status'
alias gba='git branch -a'
alias tls='tmux list-sessions'
alias ta='tmux attach -t'
alias clj='rlwrap -a dummy clj'
alias zs='source ~/.zshrc'
alias pyclean='find . -type f -name "*.py[co]" -delete'
alias mkproject='mkproject -t locodev'
