windows:
  - name: vim-project
    splits:
      - cmd:
        height : 100
      - cmd:
        width: 50
      - cmd:
        widht: 50
      - cmd:
        widht: 50
      - cmd:
        width: 50

