windows:
  - name: vim-project
    splits:
      - cmd:
        - clear
      - cmd:
        - clear
      - cmd: clear
        height: 50
        target: bottom-right
      - cmd: clear
        height: 50
        target: bottom-left
