windows:
  - name: vim-project
    splits:
      - cmd:
        - clear
      - cmd:
        - clear
        width : 50
      - cmd:
        - clear
        width: 50
      - cmd:
        - clear
        height: 50
      #- cmd:
        #- clear
        #width: 50

#.------------------.------------------.
#|                  |        |         |
#|                  |        |         |
#|                  |        |         |
#|                  |        |         |
#|                  |------------------|
#|                  |        |         |
#|                  |        |         |
#|                  |        |         |
#|                  |        |         |
#'------------------'------------------'
