#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>


export PATH="/opt/homebrew/bin":$PATH
export PATH="/Library/TeX/texbin":$PATH
export PATH=$HOME/.cargo/bin:$PATH
#export PATH="$HOME/.pyenv/versions/miniforge3-4.10.1-5/bin:$PATH"
#export PATH=$(brew --prefix openssh)/bin:$PATH

#export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/zlib/lib -L/usr/local/opt/bzip2/lib"
#export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include  -I/usr/loca/opt/zlib/include -I/usr/local/opt/bzip2/include"


#export GNUPGHOME=~/.gnupg/trezor

export PIPENV_IGNORE_VIRTUALENVS=1

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi


export GITLAB_USER=jameknas
export GITLAB_TOKEN="ofsHcctybx14HBC5MLKN"

export PYENV_VIRTUALENV_DISABLE_PROMPT=1

#export TERM=xterm-256color
#

# export BAT_THEME='gruvbox'

# export FZF_DEFAULT_COMMAND='rg --files --follow --glob "!.git/*"'
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow --glob "!.git/*"'
. "$HOME/.cargo/env"

export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_NO_INSECURE_REDIRECT=1
export HOMEBREW_CASK_OPTS=--require-sha
