#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
setopt interactivecomments
bindkey -M viins "jj" vi-cmd-mode
export TERM=xterm-256color
setopt interactivecomments
source $HOME/.dotfiles/aliases.zsh
source $HOME/.profile
